@Library("jenlib") _

boolean executeHwTests = [
		!isTriggeredByGerrit(),
		env.GERRIT_PROJECT == "calix"
].any({ it })

Map<String, Object> pipelineOptions = [
		projects           : ["calix"],
		container          : [app: "dls"],
		notificationChannel: "#dls-software",
		configureInstallOptions: "--build-profile=ci"
]

if (executeHwTests) {
	pipelineOptions << [
			testOptions      : "--test-execall -j1",
			testSlurmResource: [partition: "cube",
			                    wafer: 62,
			                    "fpga-without-aout": 3,
			                    "cpus-per-task": 8,
			                    time: 120],
			preTestHook      : { configureHxCubeBitfile() },
	]
}

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}

stage("finalization") {
	runOnSlave(label: "frontend") {
		archiveArtifacts artifacts: 'calix/multiplication_synin.png',
		    allowEmptyArchive: true
		archiveArtifacts artifacts: 'calix/calib_eval.npz',
		    allowEmptyArchive: true
		archiveArtifacts artifacts: 'calix/calibs/',
		    allowEmptyArchive: true
		archiveArtifacts artifacts: 'calix/coba_modulation.png',
		    allowEmptyArchive: true
	}
}
