@Library("jenlib") _

wafDefaultPipeline(projects: ["calix"],
                   container: [app: "visionary-dls"],
                   testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
                   testTimeout: 600,
                   testOptions: "-j1 --test-execall",
                   notificationChannel: "#dls-software")
